version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install 
  pre_build:
    commands:
      - chmod +x cf.sh
  build:
    commands: 
      - node -v
      - npm -v
      - npm run deploy
artifacts:
  files:  
    - '**/*'