version: 0.2

phases:
  before_install:
    commands: 
      - chmod +x cf.sh
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install 
  build:
    commands: 
      - node -v
      - npm -v
      - npm run deploy
artifacts:
  files:  
    - '**/*'